### ISSUE TITLE
https://www.lete114.top

### ISSUE THREAD

**Issue by DreamyTZK** [DreamyTZK/friend#1]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: Lete乐特
# 跳转地址
link: https://www.lete114.top
# 你的头像
avatar: https://www.lete114.top/img/avatar.png
# 你的描述
descr: 人生只有一次，大胆的生活！！
# 边框及鼠标悬停的背景颜色，允许设置渐变色
--primary-color: linear-gradient( 135deg, #FFF886 10%, #F072B6 100%)
# 边框大小
border-width: 1px
# 边框样式
border-style: solid
# 边框动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：borderFlash（边框闪现）、link_custom1(跑马灯)、link_custom(主颜色呼吸灯)
animation: link_custom1 1s infinite alternate

# 鼠标悬停头像旋转角度
--primary-rotate: 0deg

# 头像动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：auto_rotate_left（左旋转）、auto_rotate_right（右旋转）
img_animation: auto_rotate_left .5s linear infinite

# 风格 可选项 item和card
card_style: card
# 自定义屏幕截图
screenshot: https://7.dusays.com/2021/01/12/42c99956eac68.png
```
